---
# module: nmos-joint-ri-setup/tasks
# description: Provision NMOS Joint RI VM

- name: Install all required packages for nmos-joint-ri-setup
  apt: 
    pkg: "{{ packages }}"
    state: present

- name: Install Apache2 modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items: "{{ apache_modules }}"
    
- name: Remove default Apache conf files
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apache2/sites-enabled/000-default.conf
  notify: Restart apache service

- name: Add ipstudio user
  user:
    name: ipstudio
