---
# name: nmos-install/defaults
# description: ALL our default variables for nmos-install go in here

packages:  # Packages required
  - python-pip 
  - python3-pip 
  - python-mock 
  - python3-mock 
  - devscripts 
  - debhelper 
  - equivs 
  - python3-setuptools 
  - python-stdeb 
  - python3 
  - libffi-dev 
  - tox
  - build-essential  # MDNS Bridge
  - libsystemd-dev
  - apache2          # Reverse Proxy
  - apache2-bin # (>=2.4.18)  # or libapache2-mod-proxy-html, ssl-cert, libxml2-dev
