---
# Provision base image
- name: Provision NMOS server
  hosts: all
  become: yes
  roles:
    - nmos-joint-ri-setup

# Install each service defined in dev_package_install_list variable
- hosts: all
  become: yes
  tasks:
    - name: NMOS service install
      include_role:
        name: nmos-service-install
      vars:
        package_name: "{{ item.package_name }}"
        repo_url: "{{ item.repo_url }}"
        branch: "{{ lookup('env', item.branch) | default('master', true) }}"
        service_file: "{{ item.service_file|default([]) }}"
        reverse_proxy_file: "{{ item.reverse_proxy_file|default([]) }}"
        required_debs: "{{ item.required_debs | default([]) }}"
      with_items: "{{ packages_to_install }}"

- hosts: node
  become: yes
  roles:
    - nmos-connectionmanagement-ui
