---
# module: nmos-install/tasks
# description: Install NMOS services and dependencies 

- name: Install all required packages for nmos-install
  apt: pkg={{ packages }} state=present

- name: Clone repo
  git:
    repo: "{{ item.repo_url }}"
    dest: "/home/vagrant/{{ item.package_name }}"
    version: "{{ item.branch }}"
  with_items: "{{ dev_packages_list }}"

- name: Install python package and dependencies
  pip:
    name: "."
    chdir: "/home/vagrant/{{ item.package_name }}"
    extra_args: "--no-binary {{ item.package_name }}"
    executable: pip2
  with_items: "{{ dev_packages_list }}"
  notify: Restart python service

- name: Change directory permissions for nmosauth config files
  file:
    path: /var/nmosauth
    owner: ipstudio
    group: ipstudio
    recurse: yes

- name: Create service file
  copy:
    src: "/home/vagrant/{{ item.package_name }}/debian/{{ item.service_file }}"
    dest: /lib/systemd/system
    remote_src: yes
  with_items: "{{ dev_packages_list }}"
  notify: Restart python service

- name: Copy apache conf file
  copy:
    src: "/home/vagrant/{{ item.package_name }}/debian/{{ item.reverse_proxy_file }}"
    dest: /etc/apache2/sites-available/
    owner: root
    group: root
    mode: '0644'
    remote_src: yes
  with_items: "{{ dev_packages_list }}"
  notify: Restart apache service