---
# module: nmos-auth-install/tasks
# description: Install NMOS Auth Server

- name: Move bin file
  copy:
    src: /home/vagrant/nmos-auth-server/bin/nmosauth
    dest: /usr/bin/nmosauth
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- name: Make directory for nmosauth config
  become: true
  file:
    path: /var/nmosauth
    owner: ipstudio
    group: ipstudio
    state: directory

- name: Generate certificate
  command: /home/vagrant/nmos-auth-server/nmosauth/certs/generate_cert.sh

- name: Create nmosauth service file
  copy:
    src: /home/vagrant/nmos-auth-server/debian/python-nmos-auth.service
    dest: /lib/systemd/system
    remote_src: yes
  notify: Restart nmosauth service
