---
# module: nmos-service-install/tasks
# description: Install NMOS service and its dependencies

- name: Clone repo
  git:
    repo: "{{ repo_url }}"
    dest: "/home/vagrant/{{ package_name }}"
    version: "{{ branch }}"

- name: Install python package and dependencies
  pip:
    name: "."
    chdir: "/home/vagrant/{{ package_name }}"
    extra_args: "--no-binary {{ package_name }}"
    executable: pip2

- name: Create service file
  copy:
    src: "/home/vagrant/{{ package_name }}/debian/{{ service_file }}"
    dest: /lib/systemd/system
    remote_src: yes

- name: Copy Apache2 conf file
  copy:
    src: "/home/vagrant/{{ package_name }}/debian/{{ reverse_proxy_file }}"
    dest: /etc/apache2/sites-available/
    owner: root
    group: root
    mode: '0644'
    remote_src: yes

- name: Enable Apache sites
  file:
    src: "/etc/apache2/sites-available/{{ reverse_proxy_file }}"
    dest: /etc/apache2/sites-enabled/{{ reverse_proxy_file }}
    state: link

- name: Restart service
  systemd:
    name: "{{ service_file }}"
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart Apache service
  systemd:
    name: apache2.service
    state: restarted
    enabled: true
    daemon_reload: true
