---
# module: nmos-connectionmanagement-ui/tasks
# description: Install NMOS connection management UI

- name: Copy share
  command: cp -r /home/{{ ansible_facts['env']['SUDO_USER'] }}/connectionmanagement/share/ipp-connectionmanagement /usr/share

- name: Copy site
  command: cp -r /home/{{ ansible_facts['env']['SUDO_USER'] }}/connectionmanagement/var/www/{{ item }} /var/www
  with_items:
    - connectionManagementDriver
    - connectionManagementUI

- name: Copy Apache2 conf file
  copy:
    src: "/home/{{ ansible_facts['env']['SUDO_USER'] }}/connectionmanagement/debian/nmos-ui.conf"
    dest: /etc/apache2/sites-available/
    owner: root
    group: root
    mode: '0644'
    remote_src: yes
  notify: Restart apache service

- name: Enable Apache sites
  file:
    src: "/etc/apache2/sites-available/nmos-ui.conf"
    dest: /etc/apache2/sites-enabled/nmos-ui.conf
    state: link
  notify: Restart apache service
