---
# name: nmos-auth-reverse-proxy/handlers
# description: Restart apache if need be

- name: Restart apache service
  systemd:
    name: apache2.service
    state: restarted
    enabled: true
    daemon_reload: true
