---
# name: nmos-install/handlers
# description: Restart services if need be

- name: Restart python service
  systemd:
    name: "{{ item.service_file }}"
    state: restarted
    enabled: true
    daemon_reload: true
  with_items: "{{ dev_packages_list }}"

- name: Restart apache service
  systemd:
    name: apache2.service
    state: restarted
    enabled: true
    daemon_reload: true
